### PR TITLE
Script for compiling NAM controllers

### PR DESCRIPTION
**Pull request by memo33**
This automates the process of creating the controllers for release, using a bash script.

There is a [new release of the compiler](https://github.com/memo33/NAMControllerCompiler/releases/tag/2.0.0) for this purpose, which is automatically downloaded by the script.

Usage:

    ./src/scripts/compile-release-controllers.sh "<version>"

Feel free to make any other adjustments.

### CODE REVIEW

**Comment by jflann** [comment]
I had to get install wget, but once I had that sorted out it worked as expected.  Thanks!

**Comment by memo33** [comment]
Did you use git-bash, or bash from Ubuntu/WSL? We could replace `wget` by `curl` if that's available by default.

**Comment by jflann** [comment]
I used git-bash, which does appear to have curl installed by default.

A few other thoughts - would it be possible to modify the script to take an optional second argument for copying the resulting files into another directory (e.g. my build directory)?

I would also very much appreciate a script like this one for the INRULs.  I'm currently using a simple windows batch script.

**Comment by memo33** [comment]
I've replaced `wget` by `curl` and added a second script for the INRULs. This should be good to go now.

**Comment by jflann** [comment]
Thanks!

**Pull request merged**
