### PR TITLE
fix syntax problems in RHW INRUL file

### PR DESCRIPTION
**Pull request by memo33**
Please review carefully.

This comments out all type-3 lines for which a corresponding type-2 line does not exist.

The LHD file still needs to be updated accordingly.

### CODE REVIEW

**Comment by jflann** [comment]
Do we suspect that the game just ignores orphan type 3 lines?  In other words, is this just cleanup with no effect on the functionality?  Wondering if any has been or should be done.

**Comment by jflann** [comment]
Actually, it seems these lines actually are having an effect.

image

Look at the definition of the 8C Type B2 ramp.  Before these changes, when this pattern is drawn, the stub is converted to RHW-6C/8C/10C median.  I could not find any other RUL that explains this behavior.

**Comment by memo33** [comment]
Thanks for catching that. My understanding was wrong. It looks like these tiles are implicitly treated as `?,?,?,?`. For example, this means the INRUL override breaks down if one of the orphan tiles is neither empty nor purely Dirtroad, but a different network, such as:

This deconverts once you click on the RHW ramp.

If this was the original intent, I guess it does not hurt to keep the code as is, so we can close this. (Instead, an update of the INRUL viewer may be in order.)

**Comment by jflann** [comment]
Not sure on the intent of all of the examples, but they could at least be made explicit by adding in the type 2 lines.  That way it's not so obfuscated and an update to the INRUL viewer might not be totally necessary

**Pull request closed without merging**
